"""add_recipients

Revision ID: 52dc3952e1e0
Revises: d5c82e600657
Create Date: 2026-06-22 17:01:28.594214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52dc3952e1e0'
down_revision: Union[str, None] = 'd5c82e600657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipients',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('external_key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_key', name='uq_recipient_tenant_external_key')
    )
    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipients_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('recipient_channel_addresses',
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient_id', 'channel', name='uq_recipient_channel')
    )
    with op.batch_alter_table('recipient_channel_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipient_channel_addresses_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipient_channel_addresses_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient_channel_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipient_channel_addresses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_recipient_channel_addresses_recipient_id'))

    op.drop_table('recipient_channel_addresses')
    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipients_tenant_id'))

    op.drop_table('recipients')
    # ### end Alembic commands ###
