"""add_channel_configs

Revision ID: a89b974f0985
Revises: a9ff87112df0
Create Date: 2026-06-22 17:32:43.479213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a89b974f0985'
down_revision: Union[str, None] = 'a9ff87112df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_configs',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sqlite.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel', name='uq_channel_config_tenant_channel')
    )
    with op.batch_alter_table('channel_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_configs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_configs_tenant_id'))

    op.drop_table('channel_configs')
    # ### end Alembic commands ###
