"""notification_fanout_and_users_split

Revision ID: a9ff87112df0
Revises: 52dc3952e1e0
Create Date: 2026-06-22 17:13:34.449482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a9ff87112df0'
down_revision: Union[str, None] = '52dc3952e1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_requests',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('channels', sqlite.JSON(), nullable=False),
    sa.Column('recipient_ids', sqlite.JSON(), nullable=False),
    sa.Column('variables', sqlite.JSON(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_notification_request_idempotency')
    )
    with op.batch_alter_table('notification_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_requests_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('notification_channels',
    sa.Column('notification_request_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('rendered_subject', sa.String(length=500), nullable=True),
    sa.Column('rendered_body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('skipped_recipients', sqlite.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_request_id'], ['notification_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_request_id', 'channel', name='uq_notification_channel_request_channel')
    )
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_channels_notification_request_id'), ['notification_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_channels_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_channels_tenant_id'), ['tenant_id'], unique=False)

    # delivery_attempts must be detached from notifications BEFORE
    # notifications is dropped — otherwise batch mode's table reflection
    # fails trying to resolve the (about to be gone) FK target.
    with op.batch_alter_table('delivery_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_channel_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=False))
        batch_op.drop_index(batch_op.f('ix_delivery_attempts_notification_id'))
        batch_op.create_index(batch_op.f('ix_delivery_attempts_notification_channel_id'), ['notification_channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_attempts_recipient_id'), ['recipient_id'], unique=False)
        # The original FK on notification_id was created unnamed by SQLite;
        # it cannot be drop_constraint'd by name. Dropping the column below
        # removes it implicitly when batch mode recreates the table.
        batch_op.create_foreign_key(
            'fk_delivery_attempts_recipient_id', 'recipients', ['recipient_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.create_foreign_key(
            'fk_delivery_attempts_notification_channel_id',
            'notification_channels',
            ['notification_channel_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.drop_column('notification_id')
        batch_op.drop_column('recipient')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_tenant_id'))

    op.drop_table('notifications')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_check_constraint(
            'ck_user_role_tenant_scope',
            "(role = 'platform_admin' AND tenant_id IS NULL) OR (role = 'tenant_admin' AND tenant_id IS NOT NULL)",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_user_role_tenant_scope', type_='check')

    # notifications must exist again BEFORE delivery_attempts re-adds its FK
    # to it — batch mode reflection needs the target table to be present.
    op.create_table('notifications',
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('template_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('channel', sa.VARCHAR(length=20), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('recipients', sqlite.JSON(), nullable=False),
    sa.Column('context', sqlite.JSON(), nullable=False),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name=op.f('uq_notification_idempotency'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    with op.batch_alter_table('delivery_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('notification_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint('fk_delivery_attempts_recipient_id', type_='foreignkey')
        batch_op.drop_constraint('fk_delivery_attempts_notification_channel_id', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_delivery_attempts_notification_id', 'notifications', ['notification_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.drop_index(batch_op.f('ix_delivery_attempts_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_attempts_notification_channel_id'))
        batch_op.create_index(batch_op.f('ix_delivery_attempts_notification_id'), ['notification_id'], unique=False)
        batch_op.drop_column('address')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('notification_channel_id')

    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_channels_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notification_channels_status'))
        batch_op.drop_index(batch_op.f('ix_notification_channels_notification_request_id'))

    op.drop_table('notification_channels')
    with op.batch_alter_table('notification_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_requests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notification_requests_status'))

    op.drop_table('notification_requests')
    # ### end Alembic commands ###
